In [1]:
import numpy as np
import gzip
import theano
from keras.models import load_model
import tensorflow as tf

Using TensorFlow backend.


In [6]:
def get_test():
    
    f = open('datasetTranskay/cb513+profile_split1.npy.gz', 'rb')
    cb513 = np.load(f)
    cb513 = np.reshape(cb513, (514, 700, 57))
    cb513 = cb513[:, :, :].astype(theano.config.floatX)

    return cb513

In [7]:
cb513 = get_test()

In [ ]:
for i in range(700):
    print(cb513[0,i,0:21])
    print(cb513[0,i,22:30])
    if(cb513[0,i,0:21].sum() == 0):
        print(i)
    if(cb513[0,i,22:30].sum() == 0):
        print(i)        

In [74]:
path = "699-Guilermo-Dropout-0.5.hdf5"
m = load_model( path )

In [112]:
from IPython.display import clear_output
import random

allValidWindows = []
all_targets = []

for i in range(cb513.shape[0]):
    
    print("protein nr " ,i)
    clear_output(wait=True)
    
    last_index = 0
    #ground truth
    for k in range(700):
        ground_truth = cb513[i,k,22:30]
        
        if(ground_truth.sum() == 0):
            break
        all_targets.append(ground_truth)
    
    #creating padding version so we do not loose information
    padded = np.zeros((700+18, 57))
    padded[9:709] = cb513[i]
    
    for k in range(9):
        padded[k] = cb513[i,0]
    for k in range(709,718):
        padded[k] = cb513[i,699]
    
    #making predictions
    predictions = []
    for k in range(718 - 19 + 1):

        if cb513[i,k,0:21].sum() == 0:
            break
        #make sure to check PSSM or 1 hot
        window =  padded[k:k+19, 35:56]
        allValidWindows.append(window)

scores = m.evaluate(np.array(allValidWindows), np.array(all_targets))
print("Loss: " + str(scores[0]) + ", Accuracy: " + str(scores[1]) + ", MAE: " + str(scores[2]))

 3488/84765 [>.............................] - ETA: 53s

KeyboardInterrupt: 

In [99]:
for i in range(718):
    if i<9:
        print(padded[i,0:21])
    
    if i >= 9 and i <= 708:
        print(padded[i,0:21].all() == cb513[0,i-9,0:21].all())
    
    if i > 708:
        print(padded[i,0:21])

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
